### ISSUE TITLE
Groovy syntax on GitHub

### ISSUE THREAD

**Issue by ewels** [nextflow-io/examples#3]
You can get GitHub to play nicely with the NextFlow scripts file extensions with these two tricks:

Add the following to the top of every `.nf` script: (does syntax highlighting)
```
vim: syntax=groovy
-*- mode: groovy;-*-
```

Create a file called `.gitattributes` with the following: (changes the coloured bar at the top of the repo to say _100% Groovy_ instead of _100% Shell_.
```
*.nf linguist-language=Groovy
```

Hope this helps! It was annoying me on our NextFlow repos 😉

**Comment by pditommaso** [comment]
Nice! I'm bit confused with the first tip. It does not break the nextflow script if you put that at the top of the file?

**Comment by ewels** [comment]
Sorry, just _near_ the top of the file. eg: https://github.com/SciLifeLab/NGI-RNAseq/blob/master/main.nf#L3-L4

**Comment by ewels** [comment]
I take it back - they can go anywhere in the file. See https://github.com/github/linguist#using-emacs-or-vim-modelines

**Comment by pditommaso** [comment]
Cool! So in a comment like this: 

```
/*
vim: syntax=groovy
-*- mode: groovy;-*-
*/
```

**Comment by ewels** [comment]
Exactly, yup 👍
